# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea7bfca1a490bcfc1483ce122812e44652583f4a3601384156d2cd39f5fb54758b42232976f94d0079b0e87e557c9f2e75f256b590ca418809c677833de14e4

test:
  secret_key_base: 9b095b9bd6ac2a5717b0af803d716c43023e406212b291d84e625d859e51995e66c7f927b50b933715960dd3e57d4e5e36c63bfca527e5e4b1ed99f47c7ae85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
